[mypy]
ignore_missing_imports = True
exclude = (?x)(
    ^app/routers/extended\.py$ |
    ^app/routers/auth\.py$ |
    ^app/routers/admin\.py$ |
    ^app/routers/widgets\.py$ |
    ^app/main\.py$
  )
