"""add_sync_privacy

Revision ID: 756d4efbbf12
Revises: 9a1ddf223cf8
Create Date: 2026-08-14 21:13:21.594598

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '756d4efbbf12'
down_revision: str | Sequence[str] | None = '9a1ddf223cf8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('sync_privacy', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'sync_privacy')
    # ### end Alembic commands ###
