"""remove review rating and add cooldowns

Revision ID: 9a1ddf223cf8
Revises: a8e43d06e4ac
Create Date: 2026-07-29 19:51:24.904106

"""
from typing import Sequence, Union


from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a1ddf223cf8'
down_revision: str | Sequence[str] | None = 'a8e43d06e4ac'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('favorite_artist_updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_profiles', sa.Column('favorite_track_updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_profiles', sa.Column('favorite_album_updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('user_profiles', 'favorite_artist_review')
    op.drop_column('user_profiles', 'favorite_track_review')
    op.drop_column('user_profiles', 'favorite_artist_rating')
    op.drop_column('user_profiles', 'favorite_album_review')
    op.drop_column('user_profiles', 'favorite_album_rating')
    op.drop_column('user_profiles', 'favorite_track_rating')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('favorite_track_rating', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user_profiles', sa.Column('favorite_album_rating', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user_profiles', sa.Column('favorite_album_review', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_profiles', sa.Column('favorite_artist_rating', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user_profiles', sa.Column('favorite_track_review', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_profiles', sa.Column('favorite_artist_review', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user_profiles', 'favorite_album_updated_at')
    op.drop_column('user_profiles', 'favorite_track_updated_at')
    op.drop_column('user_profiles', 'favorite_artist_updated_at')
    # ### end Alembic commands ###
