"""Init pg

Revision ID: 9a3f99ad184d
Revises: 
Create Date: 2026-06-03 22:27:07.890489

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a3f99ad184d'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

USERS_ID = 'users.id'


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('rule_type', sa.String(), nullable=True),
    sa.Column('rule_value', sa.Integer(), nullable=True),
    sa.Column('rule_target', sa.String(), nullable=True),
    sa.Column('rule_meta', sa.String(), nullable=True),
    sa.Column('target_image', sa.String(), nullable=True),
    sa.Column('reward_xp', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_achievements_id'), 'achievements', ['id'], unique=False)
    op.create_table('tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('artist', sa.String(), nullable=True),
    sa.Column('cover_url', sa.String(), nullable=True),
    sa.Column('track_url', sa.String(), nullable=True),
    sa.Column('album', sa.String(), nullable=True),
    sa.Column('genre', sa.String(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracks_album'), 'tracks', ['album'], unique=False)
    op.create_index(op.f('ix_tracks_artist'), 'tracks', ['artist'], unique=False)
    op.create_index(op.f('ix_tracks_genre'), 'tracks', ['genre'], unique=False)
    op.create_index(op.f('ix_tracks_id'), 'tracks', ['id'], unique=False)
    op.create_index(op.f('ix_tracks_title'), 'tracks', ['title'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_api_key'), 'users', ['api_key'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('follows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('following_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['follower_id'], [USERS_ID], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['following_id'], [USERS_ID], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_follows_id'), 'follows', ['id'], unique=False)
    op.create_table('scrobbles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('played_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('listened_sec', sa.Integer(), nullable=True),
    sa.Column('is_playing', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('xp_earned', sa.Integer(), nullable=True),
    sa.Column('is_imported', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], [USERS_ID], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrobbles_id'), 'scrobbles', ['id'], unique=False)
    op.create_index(op.f('ix_scrobbles_track_id'), 'scrobbles', ['track_id'], unique=False)
    op.create_index(op.f('ix_scrobbles_user_id'), 'scrobbles', ['user_id'], unique=False)
    op.create_table('user_achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('achievement_id', sa.Integer(), nullable=True),
    sa.Column('earned_at', sa.DateTime(), nullable=True),
    sa.Column('is_displayed', sa.Boolean(), nullable=True),
    sa.Column('notified', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], [USERS_ID], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_achievements_id'), 'user_achievements', ['id'], unique=False)
    op.create_table('user_integrations',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bonus_xp', sa.Integer(), nullable=True),
    sa.Column('current_streak', sa.Integer(), nullable=True),
    sa.Column('last_streak_date', sa.String(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('yandex_token', sa.String(), nullable=True),
    sa.Column('lastfm_username', sa.String(), nullable=True),
    sa.Column('spotify_access_token', sa.String(), nullable=True),
    sa.Column('spotify_refresh_token', sa.String(), nullable=True),
    sa.Column('last_sync', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], [USERS_ID], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('cover_url', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('favorite_genre', sa.String(), nullable=True),
    sa.Column('equipment', sa.String(), nullable=True),
    sa.Column('social_links', sa.String(), nullable=True),
    sa.Column('theme', sa.String(), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=True),
    sa.Column('hidden_artists', sa.String(), nullable=True),
    sa.Column('favorite_artist', sa.String(), nullable=True),
    sa.Column('favorite_artist_url', sa.String(), nullable=True),
    sa.Column('favorite_artist_cover', sa.String(), nullable=True),
    sa.Column('favorite_track', sa.String(), nullable=True),
    sa.Column('favorite_track_url', sa.String(), nullable=True),
    sa.Column('favorite_track_cover', sa.String(), nullable=True),
    sa.Column('favorite_track_review', sa.String(), nullable=True),
    sa.Column('favorite_track_rating', sa.Integer(), nullable=True),
    sa.Column('favorite_album', sa.String(), nullable=True),
    sa.Column('favorite_album_url', sa.String(), nullable=True),
    sa.Column('favorite_album_cover', sa.String(), nullable=True),
    sa.Column('favorite_album_review', sa.String(), nullable=True),
    sa.Column('favorite_album_rating', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], [USERS_ID], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('scrobble_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('scrobble_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scrobble_id'], ['scrobbles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], [USERS_ID], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrobble_comments_id'), 'scrobble_comments', ['id'], unique=False)
    op.create_table('scrobble_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('scrobble_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scrobble_id'], ['scrobbles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], [USERS_ID], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrobble_likes_id'), 'scrobble_likes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scrobble_likes_id'), table_name='scrobble_likes')
    op.drop_table('scrobble_likes')
    op.drop_index(op.f('ix_scrobble_comments_id'), table_name='scrobble_comments')
    op.drop_table('scrobble_comments')
    op.drop_table('user_profiles')
    op.drop_table('user_integrations')
    op.drop_index(op.f('ix_user_achievements_id'), table_name='user_achievements')
    op.drop_table('user_achievements')
    op.drop_index(op.f('ix_scrobbles_user_id'), table_name='scrobbles')
    op.drop_index(op.f('ix_scrobbles_track_id'), table_name='scrobbles')
    op.drop_index(op.f('ix_scrobbles_id'), table_name='scrobbles')
    op.drop_table('scrobbles')
    op.drop_index(op.f('ix_follows_id'), table_name='follows')
    op.drop_table('follows')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_api_key'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tracks_title'), table_name='tracks')
    op.drop_index(op.f('ix_tracks_id'), table_name='tracks')
    op.drop_index(op.f('ix_tracks_genre'), table_name='tracks')
    op.drop_index(op.f('ix_tracks_artist'), table_name='tracks')
    op.drop_index(op.f('ix_tracks_album'), table_name='tracks')
    op.drop_table('tracks')
    op.drop_index(op.f('ix_achievements_id'), table_name='achievements')
    op.drop_table('achievements')
    # ### end Alembic commands ###
