"""Add missing indexes and optimize lazy loads

Revision ID: c499796633a6
Revises: 9a3f99ad184d
Create Date: 2026-06-03 23:04:39.307991

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c499796633a6'
down_revision: str | Sequence[str] | None = '9a3f99ad184d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_follows_follower_id'), 'follows', ['follower_id'], unique=False)
    op.create_index(op.f('ix_follows_following_id'), 'follows', ['following_id'], unique=False)
    op.create_index(op.f('ix_scrobble_comments_scrobble_id'), 'scrobble_comments', ['scrobble_id'], unique=False)
    op.create_index(op.f('ix_scrobble_comments_user_id'), 'scrobble_comments', ['user_id'], unique=False)
    op.create_index(op.f('ix_scrobble_likes_scrobble_id'), 'scrobble_likes', ['scrobble_id'], unique=False)
    op.create_index(op.f('ix_scrobble_likes_user_id'), 'scrobble_likes', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_achievements_achievement_id'), 'user_achievements', ['achievement_id'], unique=False)
    op.create_index(op.f('ix_user_achievements_user_id'), 'user_achievements', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_achievements_user_id'), table_name='user_achievements')
    op.drop_index(op.f('ix_user_achievements_achievement_id'), table_name='user_achievements')
    op.drop_index(op.f('ix_scrobble_likes_user_id'), table_name='scrobble_likes')
    op.drop_index(op.f('ix_scrobble_likes_scrobble_id'), table_name='scrobble_likes')
    op.drop_index(op.f('ix_scrobble_comments_user_id'), table_name='scrobble_comments')
    op.drop_index(op.f('ix_scrobble_comments_scrobble_id'), table_name='scrobble_comments')
    op.drop_index(op.f('ix_follows_following_id'), table_name='follows')
    op.drop_index(op.f('ix_follows_follower_id'), table_name='follows')
    # ### end Alembic commands ###
